# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  webproject2022:
    image: webproject2022
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5115:5115
